### PR TITLE
remove duplicated hdfs configs

### PR DESCRIPTION
**Pull request by haoyuan**

### CODE REVIEW

**Comment by pwendell** [comment]
Hey @haoyuan - where are these duplicated? I think the short circuit read settings need to be present in multiple places, because you want both the HDFS client and the HDFS data node to read them...

**Comment by haoyuan** [comment]
@pwendell , you are right. About "dfs.blocksize", there is another "dfs.block.size" in the same file.

**Comment by pwendell** [comment]
That's because the parameter is named differently in Hadoop1 and Hadoop2 and we want to support either one.

**Comment by haoyuan** [comment]
I see. No worries then.

**Pull request closed without merging**
