### PR TITLE
Set SPARK_PUBLIC_DNS in spark-env.sh (to address SPARK-833)

### PR DESCRIPTION
**Pull request by JoshRosen**
This is intended to address [SPARK-833](https://spark-project.atlassian.net/browse/SPARK-833), an issue where Spark web UIs might be bound to non-public addresses when running on EC2.  We had previously solved this problem for the Master and Worker UIs, but `SPARK_PUBLIC_DNS` needs to be set in the driver's environment in order for its application web UI to bind to the correct public address.

### CODE REVIEW

**Comment by shivaram** [comment]
Why dont we just set this in spark-env.sh ? You can do that by modifying the spark-env.sh in `templates`

**Comment by JoshRosen** [comment]
I was worried about cases where someone might launch their driver without sourcing spark-env.sh first.

On the other hand, things can break in various subtle ways if the driver's settings don't match the settings in spark-env.sh (for example, adding `export PYSPARK_PYTHON=python27` to use Python 2.7, then forgetting to source this in an IPython notebook driver can cause the driver and worker Python processes to use different Python versions).

I'm running out the door now, but I can update this later to put the setting in spark-env.sh instead.

**Comment by shivaram** [comment]
Yeah - Since the EC2 scripts are predominantly meant for trying out spark and since `spark-shell` and `run-example` source spark-env.sh, I think that should be sufficient. If somebody wants similar settings in their driver, they can copy  settings from `spark-env.sh`.

**Comment by JoshRosen** [comment]
I updated this pull request to set it in spark-env.sh instead of in .bash_profile.

**Comment by shivaram** [comment]
Looks good. Thanks Josh.

**Pull request merged**
