### PR TITLE
Support Spark 1.1.1

### PR DESCRIPTION
**Pull request by andrewor14**
@shivaram can you merge this

### CODE REVIEW

**Comment by shivaram** [comment]
LGTM. Merging this

**Comment by jey** [comment]
I'm running into this problem still -- I just launched a Spark 1.1.1 cluster on EC2 and got a `/root/spark` dir that was empty except for the `conf` directory.

**Comment by shivaram** [comment]
Do you have the output from running spark_ec2.py ? It'll be great if you can put it in a gist or something like that

**Comment by jey** [comment]
@shivaram, good point. I filed [SPARK-4731](https://issues.apache.org/jira/browse/SPARK-4731) for this issue and will post full logs there tomorrow

**Comment by andrewor14** [comment]
Hey @jey thanks for reporting this I just tried it out and ran into it myself. Actively investigating.

**Comment by andrewor14** [comment]
Aha looks like Spark 1.1 branch is still using `spark-ec2` branch v3, not v4. This PR was merged into v4. I have opened a new PR #82 against the correct `spark-ec2` branch. This should work once @shivaram merges that one.

**Pull request merged**
