### PR TITLE
Disable Transparent Huge Pages.

### PR DESCRIPTION
**Pull request by rxin**
See examples online from various system vendors recommending turning THP off:
http://blog.couchbase.com/often-overlooked-linux-os-tweaks
https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/InstallationGuide/BeforeYouInstall/transparenthugepages.htm
http://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH4/4.2.2/CDH4-Installation-Guide/cdh4ig_topic_11_6.html

Information on THP: 
http://www.slideshare.net/raghusiddarth/transparent-hugepages-in-rhel-6

dstat/perf trace when the problem happens:
https://gist.github.com/rxin/eac982fe23396d5efddf

### CODE REVIEW

**Comment by pwendell** [comment]
Should we document this somewhere prominent in Spark? In the past I saw
this huge system overhead. I found it happened if I was trying to use all
the cores on each machine, and it went away if I left the OS a few cores.

This is an awesome find.

**Comment by shivaram** [comment]
This is very cool. Yeah we should document this somewhere prominent. 

Also @rxin, did you have to do anything special to setup `perf` on EC2 ? If you did, it will be great to add a wiki describing how to use perf

**Comment by rxin** [comment]
Yes, I had to install perf. Actually there are a bunch of tools I install every time on these machines. We can probably install them by default onto the ami.

**Comment by shivaram** [comment]
Yeah we could put them on the AMI or also just add them with `yum install -q -y` in setup-slave.sh as a workaround

**Comment by etrain** [comment]
Do we have a sense about the downsides of turning this off? E.g. if each executor is managing a large set of virtual pages and gets context-switched, won't a much larger TLB cache need to get flushed out - deteriorating performance if spark's thread pools are big.

Also, there's a note in the couchbase post which encourages dropping swappiness to 0. If executor VMs are using close to total system memory, as is often the case with spark apps, won't this cause a bunch of swapping? Has anyone played with this setting on ec2 before?

**Comment by rxin** [comment]
Swapping is disabled by default on spark-ec2

**Comment by shivaram** [comment]
Hmm - in that case we should probably get rid of https://github.com/rxin/spark-ec2/blob/thp/setup-slave.sh#L100 -- This adds around 30s during cluster launch for some reason.

**Comment by rxin** [comment]
Actually mea culpa. I don't think swap is disabled by default. In any case, that belongs in a different PR ....

**Comment by etrain** [comment]
Fair enough - any idea about potential drawbacks of disabling THP? Maybe we just let spark-perf decide..

**Comment by rxin** [comment]
I don't think there are any drawbacks here ... In any case, rhel/cent is the only disto that turns it on by default (and I think in later versions it might've been off by default), and almost every vendor doc I can find recommends turning it off. (CDH manager even checks whether it is on and reports an error if it is).

**Comment by etrain** [comment]
Which AMI are you running on? When I run on the default spark AMI it looks like whatever version of CentOS I'm using doesn't have this turned on (there is no /sys/kernel/mm/transparent_hugepage/). This is on a c3.8xlarge.

**Comment by rxin** [comment]
Huge Pages I believe is only supported on the HVM instances (r3.8xlarge).

Does it throw an error if we do echo on non-HVM instances?

**Comment by etrain** [comment]
It just complains that the path doesn't exist - you could check for
existence  of the parent beforehand, I think, or not care because there's
already a bunch of not so great output from this script anyway.

**Comment by rxin** [comment]
Ok I added a check and only set it to never if that file exists.

**Comment by etrain** [comment]
Lgtm

**Comment by concretevitamin** [comment]
Out of curiosity, how long does that thrashing last? Or is it just stuck?

**Comment by rxin** [comment]
Stuck forever.

**Comment by concretevitamin** [comment]
Geez.

**Comment by rxin** [comment]
It depends on the workload. In my case I was reading a huge amount of data (larger than total memory), and that's why it was stuck forever because it constantly paged in/out buffer cache.

**Pull request merged**
