### PR TITLE
Support up to 8 EBS volumes.

### PR DESCRIPTION
**Pull request by rxin**
Please merge this at the same time as https://github.com/apache/spark/pull/2260

### CODE REVIEW

**Comment by shivaram** [comment]
Looks good. Is this or https://github.com/apache/spark/issues/2260 in anyways not backwards compatible ?

**Comment by shivaram** [comment]
Also why do we need so many EBS devices ? Can't we just have a few large ones ?

**Comment by rxin** [comment]
Higher throughput. Each EBS volume is capped at around 130MBps.

**Comment by shivaram** [comment]
Ok - I see. So I thought about this a little more and this isn't backwards compatible as older spark_ec2 scripts will use /dev/sdv as the only volume. 

To preserve backwards compatibility you can name them as sdv, sdw, sdx, sdy, sdz, sdu, sdt, sds, sdr ? (i.e. sdv, then 4 after and 4 before). Or maybe just symlinking /vol3 to /vol might be enough ?
Overall I'd suggest running spark_ec2.py from branch-1.1 with this spark-ec2 change and make sure it works.

**Comment by rxin** [comment]
Good idea. I symlinked vol3 to vol now.

I like this idea better than starting at sdv and then go around to sdu since that is more confusing.

**Comment by shivaram** [comment]
Cool. If you've tested this with the old spark_ec2.py, we can merge this.

**Comment by rxin** [comment]
Did you look at the apache spark one too? We should merge both at the same time.

**Comment by shivaram** [comment]
I took a brief look. I dont see why they need to go in at the same time ? This can go in before as its backward compatible ?

**Comment by rxin** [comment]
Oh true. Merging this please :)

**Comment by rxin** [comment]
Please also review the other one :)

**Pull request merged**
