### PR TITLE
Allow users to push S3 config details to master

### PR DESCRIPTION
**Pull request by pwendell**
This is useful if a user is using the cluster to access s3.

### CODE REVIEW

**Comment by shivaram** [comment]
Hey Patrick

Any reason to not create the `<property>` tags here and use `{{aws_id}}` as just the id, similar to say the `{{active_master}}` tag ?

**Comment by pwendell** [comment]
See the comment in the other pr

**Comment by pwendell** [comment]
Basically a blank value could override values set by other means

**Comment by shivaram** [comment]
Hmm - but then wouldn't this create a duplicate `<property>` entry in the xml file ? I see your point but I am not sure this is the right fix for that.

**Comment by pwendell** [comment]
Hey @shivaram - these credentials can be specified in two other ways than XML properties. They can be specified as command line flags to certain tools and also specified as environment variables.

What I'm trying to avoid is that someone has the pattern of doing that (e.g. say someone always uses an environment variable) and then this change breaks their existing process by adding blank values for those keys that override the ones they specify in the environment. That would be very hard to debug.

I'm not worried about users that modify the XML file themselves... in that case I'd expect them to just delete any duplicate properties.

Is there another case I'm not considering here?

**Comment by shivaram** [comment]
Ah I see - so we want to avoid having the property tag in the xml file if the flag (--s3-credentials) is not passed. 
I think the things are more readable if we can see what are the properties set in the config file without having the logic spread around multiple files.  

So my ideal solution would be for the tag to be commented out and then enabled if the flag is set, but sigh xml comments are so painful, I am not sure its worth it.

**Pull request closed without merging**
