### PR TITLE
Use 'return' instead of 'exit in init & setup scripts (SPARK-919)

### PR DESCRIPTION
**Pull request by JoshRosen**
<del>This commit addresses [SPARK-919](https://spark-project.atlassian.net/browse/SPARK-919), an issue where the `launch --resume` option could sometimes fail due to the top-level setup script exiting if the Spark module was already installed; the problem was that the `exit` command in the Spark `init.sh` script was being executed in the top-level setup script's shell.

<del>@pwendell @shivaram Was there a reason why this originally used `source` to run these scripts?  If we still need to use `source`, then we should find another way to implement defensive exits (instead of just calling `exit`: 1ac895e15c7e43f5de00123196c721c2723c9952).</del>

Update: I used `return` instead of `exit`, instead of getting rid of `source`.

### CODE REVIEW

**Comment by shivaram** [comment]
Hey Josh

So the reason I originally used `source` was to propagate environment variables to the init and setup scripts. Things like `SLAVES` etc. are parsed by the script in the root directory and then used by the modules. 

I agree that we need a better way to get out from scripts -- One way might be to use `return` ?
http://stackoverflow.com/questions/3666846/how-do-you-return-to-a-sourced-bash-script?answertab=votes#tab-top

**Comment by JoshRosen** [comment]
Ah, that makes sense.  It sounds like `return` may solve this issue; I'll test it out the next time that I launch a cluster.

**Comment by JoshRosen** [comment]
@shivaram using `return` seems to address this issue, so I updated this pull request to implement that technique.  I also added a couple of defensive `cd`s to guard against the sourced scripts returning after they changed the current working directory; this seems easier than relying on those scripts to properly reset the cwd after errors.

**Comment by shivaram** [comment]
Looks good. Thanks Josh !

**Pull request merged**
