### PR TITLE
update tachyon version

### PR DESCRIPTION
**Pull request by ghost**
Spark 1.2.1 now is built against Tachyon0.5.0, but the old spark-ec2 defaults to Tachyon0.4.1. 

This PR is a temporary fix to update Tachyon version in spark-ec2 to 0.5.0, so spark1.2.1 users can deploy to EC2 without problem.  

Also, hadoop version is taken into account. 

A further PR will be made to make Tachyon version configurable after the PR(https://github.com/apache/spark/pull/4901) is accepted.

### CODE REVIEW

**Comment by shivaram** [comment]
Is Spark 1.3 also built against Tachyon 0.5 ? Note that for Spark 1.2 you need to open a PR against branch `v4` -- See https://cwiki.apache.org/confluence/display/SPARK/spark-ec2+AMI+list+and+install+file+version+mappings for the complete mapping

**Comment by haoyuan** [comment]
Yes. Spark 1.3 is built against Tachyon 0.5.0.

**Comment by ghost** [comment]
@shivaram yes, both v3(spark 1.0 ~ 1.1) and v4 needs to be updated.

**Comment by shivaram** [comment]
LGTM. Merging this - Could you open a new PR against v4 ?

**Pull request merged**
