### PR TITLE
[branch-1.4] Support for launching YARN clusters

### PR DESCRIPTION
**Pull request by shivaram**
This is a port of #77 to branch-1.4. Additionally I added some code to handle any new Spark version in `spark/init.sh`

Tested that HDFS (ephemeral, persistent), Spark shell and SparkR work with this. 

cc @pwendell @andrewor14

### CODE REVIEW

**Comment by andrewor14** [comment]
LGTM

**Comment by shivaram** [comment]
Thanks @andrewor14 -- One last question: Do we also need to set `spark.driver.memory` for yarn client mode ? I ran into some issues earlier today without that

**Comment by andrewor14** [comment]
What issues? I didn't set `spark.driver.memory` in my testing and things seem to be working.

**Comment by shivaram** [comment]
I launched `bin/spark-shell --master yarn` and it was hanging with the  `Cluster hasn't accepted any tasks` message. It looked like it didn't launch any executors and just had the master in that case. 
I guess the `num-executors` flag is required for YARN ?

**Comment by andrewor14** [comment]
`--num-executors` should default to 2. Can you go to the RM UI @ 8088 to see if there are actually enough resources in your cluster for the executors? How much memory is your driver taking?

These are my settings:

**spark-defaults.conf**

```
spark.executor.memory 6154m
spark.executor.extraLibraryPath /root/ephemeral-hdfs/lib/native/
spark.executor.extraClassPath /root/ephemeral-hdfs/conf
```

**spark-env.sh**

```
export SPARK_LOCAL_DIRS="/mnt/spark,/mnt2/spark"

# Standalone cluster options
export SPARK_MASTER_OPTS=""
#export SPARK_WORKER_INSTANCES=1
export SPARK_WORKER_CORES=2

export HADOOP_HOME="/root/ephemeral-hdfs"
export SPARK_MASTER_IP=ec2-52-25-26-244.us-west-2.compute.amazonaws.com
export MASTER=`cat /root/spark-ec2/cluster-url`

export SPARK_SUBMIT_LIBRARY_PATH="$SPARK_SUBMIT_LIBRARY_PATH:/root/ephemeral-hdfs/lib/native/"
export SPARK_SUBMIT_CLASSPATH="$SPARK_CLASSPATH:$SPARK_SUBMIT_CLASSPATH:/root/ephemeral-hdfs/conf"

# Bind Spark's web UIs to this machine's public EC2 hostname:
export SPARK_PUBLIC_DNS=`wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname`

# Used for YARN model
export YARN_CONF_DIR="/root/ephemeral-hdfs/conf"

# Set a high ulimit for large shuffles
ulimit -n 1000000
```

**Comment by shivaram** [comment]
Hmm it was a 2 node cluster but I stopped it earlier in the morning though. I'll launch another one tonight and let you know how it goes

**Comment by andrewor14** [comment]
Yeah it's actually quite likely that your cluster actually did not have resources for the executors. My cluster is 6 `m1.large` nodes.

**Comment by shivaram** [comment]
Yep - you are right. With a similarly sized 6 node cluster, things work fine for me too. I'm going to merge this now.

Couple of things that still need work:
1. The `SPARK_WORKER_INSTANCES` commenting out bit -- @andrewor14 do you know if we can set it to some other value (like say `0` or `-1`). That might be easier to do than commenting it out in our current setup. 
1. cc @haoyuan The tachyon setup doesn't work with Hadoop 2.4 right now, we'll probably need binary packages for that.

**Comment by andrewor14** [comment]
Any setting of `SPARK_WORKER_INSTANCES` will not work. The only way is to leave it out. (See https://github.com/apache/spark/blob/master/yarn/src/main/scala/org/apache/spark/scheduler/cluster/YarnClientSchedulerBackend.scala#L73)

**Comment by shivaram** [comment]
Actually looking at the code it looks like it will work if we set it equal to `SPARK_EXECUTOR_INSTANCES` ? That should be pretty simple to do in spark_ec2.py

**Comment by andrewor14** [comment]
Are we also setting `SPARK_EXECUTOR_INSTANCES`? If not it still won't work because `SPARK_WORKER_INSTANCES` will have a value of the empty string instead, in which case we'll still add `--num-executors` to the command. I don't believe there's a value we can set it to without duplicating the default value of 2.

**Comment by shivaram** [comment]
Huh - yeah I just realized that i was talking about `SPARK_WORKER_CORES`. We don't set `SPARK_EXECUTOR_INSTANCES`. Hmm let me see if I can make this commenting thing work through some other way

**Comment by shivaram** [comment]
I have a fix for this by putting the `export` inside an `if` block -- I'm testing this out in a separate branch https://github.com/shivaram/spark-ec2/commit/6c7d1f76b92a683f3fbb36d713b783fbc5f7373c

**Comment by shivaram** [comment]
Alright that seemed to work. I pushed a new commit here and opened https://github.com/apache/spark/pull/6424 to clear the variable (the `if` clause will then prevent `SPARK_WORKER_INSTANCES` from being set)

**Comment by shivaram** [comment]
@andrewor14 I'm going to merge this one as all the PRs on the Spark side have been committed.

**Comment by andrewor14** [comment]
sg

**Pull request merged**
