### PR TITLE
SPARK-3840 - Fixed template substitution when value is None (not found on environment)

### PR DESCRIPTION
**Pull request by douglaz**

### CODE REVIEW

**Comment by douglaz** [comment]
#58 made this bug more clear

**Comment by shivaram** [comment]
@JoshRosen could you take a look at this ?

**Comment by JoshRosen** [comment]
@douglaz Is the issue here that you were using an older version of the `spark_ec2.py` script that pulled in the latest version of the `mesos/spark-ec2` templates?  If so, I could see how that might cause problems.  I guess the server-side scripts need to be backwards-compatible with earlier versions of spark-ec2.

**Comment by JoshRosen** [comment]
I created a new `v4` branch and merged this PR into it.  Thanks!

**Pull request closed without merging**
