### PR TITLE
Tweak to make script work in py3

### PR DESCRIPTION
**Pull request by meawoppl**

### CODE REVIEW

**Comment by JoshRosen** [comment]
Don't you also have to import print_function from future?

**Comment by shivaram** [comment]
Unfortunately I don't know a lot of Python -- Is this backwards compatible ? 

cc @nchammas

**Comment by nchammas** [comment]
@meawoppl Why do we need this change? Have you run into any specific issues?

The `deploy_templates.py` script is [called](https://github.com/mesos/spark-ec2/blob/74e884c7d6dd3d0c2616396ef4e98f3413ea0732/setup.sh#L99) on the launched EC2 instances, which are running Python 2.

**Comment by meawoppl** [comment]
I am using python3 on ec2.  There is a neat trick here, which is that in python2 the parens are ignored safely:

``` python
(py2)meawoppl@lena:~/repos/spark/ec2$ ipython
Python 2.7.9 |Continuum Analytics, Inc.| (default, Apr 14 2015, 12:54:25) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: print(5)
5
```

Unless you need kwarg behaviors of the print function in py2, there is no need for the print_function import.

**Comment by meawoppl** [comment]
I should add that without this, py3 will throw a syntax error and use of the spark-ec2 script will fail to expand the templates right, resulting in defaults being used for ganglia other sorted misconfigurations.

**Comment by JoshRosen** [comment]
Ah, you're right about the print_function; my bad.  When spark-ec2 failed to expand the templates, did it fail-fast or try to continue the launch even though the template update failed?

**Comment by JoshRosen** [comment]
Maybe the reason that I thought of `print_function` is that I think that importing it will cause Python 2.x to fail-fast if you try to introduce a print statement which won't work in Python 3.

**Comment by meawoppl** [comment]
Yeah.  The benefit of slapping developers is there.  I am less familiar with this repo that the spark primary, so I didn't know the general protocol.  

The launch goes on fine, and really, almost everything runs right.  (I was messing with some of the path variables manually for my purposes, so my own state is broken in a somewhat unrelated way).  Should it overtly break for this sort of configuration failure?

I get some warnings about config files being wrong etc:

```
Unpacking Tachyon
[timing] tachyon init:  00h 00m 02s
Initializing ganglia
Connection to ec2-52-25-81-108.us-west-2.compute.amazonaws.com closed.
[timing] ganglia init:  00h 00m 00s
Creating local config files...
  File "./deploy_templates.py", line 87
    print "Configuring " + dest_file
                       ^
SyntaxError: Missing parentheses in call to 'print'
Deploying Spark config files...
chmod: cannot access `/root/spark/conf/spark-env.sh': No such file or directory

....

Connection to localhost... TACHYON_WORKER_MEMORY_SIZE was not set. Using the default one: 128MB
TACHYON_RAM_FOLDER was not set. Using the default one: /mnt/ramdisk
```

I also get a warning about a ssl connection left open:

``` python
./spark_ec2.py:1448: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('xxx.xxx.xxx.xxx', 60260), raddr=('yyy.yyy.yyy.yyy', 443)>
```

but it appears to be a Python issue vs something with spark in my very limited googling.

**Comment by nchammas** [comment]
Just a note to the committers that we need to resolve [SPARK-7806](https://issues.apache.org/jira/browse/SPARK-7806) after this PR is merged.

**Comment by shivaram** [comment]
@nchammas @JoshRosen so does this change look fine from a backwards compatibility perspective ?

**Comment by JoshRosen** [comment]
Yep, looks good to me; feel free to merge.

**Comment by meawoppl** [comment]
Thanks all.  There are a few other bits I have run into lately.  
I started a jira around them:
https://issues.apache.org/jira/browse/SPARK-7909

I plan to work this some more sometime Friday.

**Pull request merged**
