### PR TITLE
make tachyon version configurable

### PR DESCRIPTION
**Pull request by ghost**
make tachyon configurable

### CODE REVIEW

**Comment by ghost** [comment]
@shivaram thanks for creating new branch.

**Comment by shivaram** [comment]
@uronce-cc - This has a merge conflict. Can you bring it up to date with `branch-1.4` ?

**Comment by ghost** [comment]
@shivaram done.

**Comment by shivaram** [comment]
The merge still has some issues. For example there is still code which looks like 

```
+<<<<<<< HEAD
+=======
+TACHYON_VERSION=0.5.0

+>>>>>>> 13efaac... update tachyon version
```

which should be cleared during merge

**Comment by ghost** [comment]
@shivaram wrongly git rebase...

**Comment by shivaram** [comment]
@uronce-cc  - It still says 'We can’t automatically merge this pull request' because your branch is not rebased on top of (or merged with) the first commit in https://github.com/mesos/spark-ec2/commits/branch-1.4

**Pull request closed without merging**
