### PR TITLE
Update Apache download links

### PR DESCRIPTION
**Pull request by nchammas**
As [requested here](https://github.com/mesos/spark-ec2/pull/78#issuecomment-61934742).

### CODE REVIEW

**Comment by nchammas** [comment]
cc @shivaram @pwendell 

Dunno if there's a better way to submit changes to multiple branches at once.

**Comment by pwendell** [comment]
I commented on the other PR - but I wasn't sure whether we needed to have
this in the older branch. It's a utility script for users, it's not
actually used by spark-ec2 anywhere.

**Comment by nchammas** [comment]
That's true. It's basically documenting how we created the AMIs that `spark-ec2` uses.

**Comment by shivaram** [comment]
Ah I see - it doesn't matter much then. Up to you @pwendell

**Comment by pwendell** [comment]
Let's keep it in the most recent branch then.

**Comment by nchammas** [comment]
Closing per Patrick's comment.

**Pull request closed without merging**
