### PR TITLE
SPARK-1302 : Fixing ganglia httpd configuration file

### PR DESCRIPTION
**Pull request by fredcons**
The httpd daemon hosting ganglia cannot launch on ami spark.ami.hvm.v14 (ami-2ae0165d), running on a m3.large instance 
This commit :
- removes / adds some apache modules to allow httpd to start and serve the ganglia php scripts
- cleans duplicate apache configuration lines
- postpones the /mnt/ganglia/rrds symlink creation after the ganglia package is installed

Any feedback welcome
This is a cherry-pick of PR #76 done on branch v4

### CODE REVIEW

**Comment by nchammas** [comment]
LGTM. Confirmed this PR is identical to the previous one with:

```
diff <(curl -s https://github.com/mesos/spark-ec2/pull/76.diff) <(curl -s https://github.com/mesos/spark-ec2/pull/95.diff)
```

**Comment by shivaram** [comment]
LGTM - I verified this by launching a cluster and it Ganglia now works. Thanks @fredcons for putting this together and @nchammas for reviewing it.

Merging this

**Comment by jey** [comment]
Should this be backported to 1.2?

**Comment by shivaram** [comment]
Yeah I'll merge https://github.com/mesos/spark-ec2/pull/76 to make this work for 1.2

**Pull request merged**
