### PR TITLE
[SPARK-5122] Remove Shark

### PR DESCRIPTION
**Pull request by nchammas**
I moved the Spark-Shark version map [to the wiki](https://cwiki.apache.org/confluence/display/SPARK/Spark-Shark+version+mapping).

This PR has a [matching PR in apache/spark](https://github.com/apache/spark/pull/3939).

### CODE REVIEW

**Comment by nchammas** [comment]
cc @shivaram

**Comment by shivaram** [comment]
LGTM. Lets wait for the Spark PR to be merged first as I want to remove 'shark' from the list of modules before we remove it here.

**Comment by nchammas** [comment]
The Spark PR has been merged.

**Comment by shivaram** [comment]
Thanks @nchammas. Merging this

**Pull request merged**
