### PR TITLE
Pulling EC2 Updates into V2 Branch

### PR DESCRIPTION
**Pull request by pwendell**
This patches the existing pull request into the v2 branch of mesos/spark-ec2. Once it's merged in, I can do some final tests and then we can merge in the mesos/spark half.

One note, the two AMI's in the registry here are private. Tomorrow I'll submit a PR with the full set of public AMI's which we can then test. I've actually written a small test suite which I plan to run in each region to make sure the AMI's have correctly been copied:

https://github.com/pwendell/spark-utils/blob/master/cluster_tests.py

Once this is thoroughly tested I'll ask to merge the one in mesos/spark.

### CODE REVIEW

**Comment by shivaram** [comment]
Hey Patrick, 

This doesn't merge with current v2 branch (which is the same as mesos/spark-ec2 HEAD). Can you update your branch to resolve this ?

**Comment by rxin** [comment]
BTW it might also be nice to squash some commits together, in particular when a lot of the commits are simple changes resulting from code review.

**Comment by pwendell** [comment]
@shivaram - thanks, will clean up.

@rxin  - ya I'll see what I can do. The history is messy because I needed to push new commits every time I was trying to debug something due to the way this repo is used.

**Comment by pwendell** [comment]
Okay @shivaram - I've brought this up to date with the master branch. I've also consolidated several of the commits that happened since the review to make things a little more sane.
- Patrick

**Comment by shivaram** [comment]
Thanks Patrick ! Merging this in.
One minor comment: The persistent-hdfs needs `mkfs.xfs`,  so we should make sure that is installed on the AMI.

**Pull request merged**
