### PR TITLE
update tachyon version

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by shivaram** [comment]
So branch v3 is used in both Spark 1.0 and Spark 1.1 -- I think Spark 1.0 was still using Tachyon 0.4 as the dependency ?

**Comment by ghost** [comment]
but 1.1 uses Tachyon0.5.0...  so?

**Comment by shivaram** [comment]
Unfortunately we can't do much about it -- we can make it work either for 1.0 or 1.1 at this point. Given that users don't frequently launch clusters with old Spark versions the hope is it shouldn't affect too many users.

**Comment by ghost** [comment]
fine.

**Pull request closed without merging**
