### PR TITLE
Adding release 1.2.2

### PR DESCRIPTION
**Pull request by pwendell**

### CODE REVIEW

**Comment by shivaram** [comment]
LGTM - one minor idea I had for making this process simpler was to just add a new rule which tries to fetch spark from wget http://s3.amazonaws.com/spark-related-packages/spark-$SPARK_VERSION-hadoop1.tgz 

Any reason to not do that ?

**Comment by pwendell** [comment]
The only downside is that if the person gives an invalid version, they'll get a slightly less helpful error message. But I agree that it's better. So want to just replace all of these if statemetns with a single rule?

**Comment by shivaram** [comment]
Yeah lets do that. We can probably do it in branch-1.4 which is the dev branch now (also chances of there being a 1.2.3 is smaller I guess). Also for error checking we could add a wget error code check, but it might be too much for a small use case

**Comment by pwendell** [comment]
Okay - then we should just merge these other two ones? I will send a new patch for 1.4

**Comment by shivaram** [comment]
Yep - lets just merge these two

**Pull request merged**
