### PR TITLE
Add realpath to fix rJava install issues

### PR DESCRIPTION
**Pull request by shivaram**
This was reported in https://groups.google.com/d/msg/sparkr-dev/7sxYNo81X8E/DJc6UsdEU0cJ

/cc @pwendell

### CODE REVIEW

**Comment by pwendell** [comment]
Looks good, but should we add this to the `create_image` script also?

**Comment by shivaram** [comment]
Updated create_image.sh -- I will also create a version for the v3 branch as Spark 1.1.1 uses v3.

**Comment by pwendell** [comment]
LGTM

**Comment by shivaram** [comment]
Thanks - Merging this

**Pull request merged**
