### PR TITLE
HOT-FIX remove wrong extra '*)'

### PR DESCRIPTION
**Pull request by dselivanov**
remove wrong extra '*)'

### CODE REVIEW

**Comment by shivaram** [comment]
Merging this. Thanks for the fix.

**Comment by shivaram** [comment]
Hi @dselivanov Could you open a similar PR for v2 branch ?

**Comment by dselivanov** [comment]
just remove "`*`)" or mb also add checking 1.0.`*` branch?

**Comment by shivaram** [comment]
No worries. @pwendell fixed it.

**Pull request merged**
