### PR TITLE
Add github.com to known_hosts

### PR DESCRIPTION
**Pull request by shivaram**

### CODE REVIEW

**Comment by rxin** [comment]
Can this be a security concern?

**Comment by shivaram** [comment]
Well its as good as hitting yes without verifying the host fingerprint showing on the screen. IMHO since almost everybody just does that, I think its fine. 

If we want to be paranoid, we could check if the fingerprint matches 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48 from https://help.github.com/articles/generating-ssh-keys

**Comment by rxin** [comment]
Maybe we should actually do that?

Or can we just put that key into the known hosts file?

**Comment by shivaram** [comment]
Hmm thats not a bad idea. It'll break if the github host key changes, but I don't think that happens frequently. We can just maintain a key file in the spark-ec2 repo and concatenate that with known_hosts ?

**Comment by rxin** [comment]
I agree - and in fact that shouldn't change too much, should it? Otherwise
it doesn't make sense for the security model.

**Pull request merged**
