### PR TITLE
Put Spark's conf ahead of Hadoop's, for log4j purposes

### PR DESCRIPTION
**Pull request by aarondav**

### CODE REVIEW

**Comment by nchammas** [comment]
@aarondav Do we still need this against `v3`?

**Comment by nchammas** [comment]
@shivaram Should we make this change against `v4` or `branch-1.3`?

**Comment by shivaram** [comment]
Lets wait for @aarondav to get back on whether this is still required. If it is we should move it to branch-1.3 first (and backport if necessary after testing)

**Comment by nchammas** [comment]
@aarondav How come this is no longer necessary?

**Comment by aarondav** [comment]
I have not kept up with the state of affairs since I made this patch, so I'm not certain if it's still necessary. We can merge this if it's desired, but I'm not sure I have the bandwidth to ensure that that's the case (i.e., experimenting on a new cluster).

**Comment by nchammas** [comment]
Fair enough. I've created a JIRA to track this so that someone else can pick it up: https://issues.apache.org/jira/browse/SPARK-4997

**Pull request closed without merging**
