### PR TITLE
Add Apache license and update README

### PR DESCRIPTION
**Pull request by shivaram**

### CODE REVIEW

**Comment by shivaram** [comment]
cc @florianverhein @pwendell @nchammas

**Comment by nchammas** [comment]
:+1: :zap: :sparkles: :beers:

**Comment by florianverhein** [comment]
Great! :)

**Comment by pwendell** [comment]
LGTM - I am happy to release all rights to any code I wrote as part of spark-ec2 under the terms of the Apache license.

**Comment by rxin** [comment]
Wait a minute - does this mean I'm going to be giving out my patches for free?!

**Comment by shivaram** [comment]
Yes @rxin - we kindly request that you license your patches under the Apache license. As you have done with the 500 other patches to https://github.com/apache/spark/commits?author=rxin

**Comment by shivaram** [comment]
Alright - since the most frequent contributors (by LOC and patches) don't have any objections I am going to merge this change.

**Pull request merged**
