### PR TITLE
V2

### PR DESCRIPTION
**Pull request by pwendell**
This makes some changes to the design to support 0.9 and future releases.
1. Scala is now installed as a module and we can use different Scala versions for different releases.
2. Support for different binary locations depending on Spark version.
3. Added spark 0.9.0 version.
4. Updated AMI (including adding R on the AMI).
5. Minor fixes.

### CODE REVIEW

**Comment by pwendell** [comment]
@shivaram I'm going to merge this because it's blocking announcing the release. However, I'm curious in any feedback you have on the approach with Scala. I tested this pretty thoroughly on old and new Spark versions. Feel free to comment on this and I can address it in a follow up PR.

**Comment by shivaram** [comment]
This looks fine -- Some minor comments and a couple of suggestions:
1. We could have created a new v3 branch to be super careful about previous releases handling things correctly. If you tested it and things are working fine, then don't bother about this.
2. We should move the Spark -> Scala version mapping to the python script spark_ec2.py -- That is a bit more elegant than bash -- We could do this when we hit 3 scala version choices at 2.11
3. Just `return` will suffice in `scala/init.sh`. I guess we should either use error codes in all places or not use them anywhere -- As we don't check the return value from init.sh, setup.sh I am okay with not using them anywhere.
4. Any reason we need the `grep -v ec2` in scala/init.sh ? I couldn't figure out why we need it

**Comment by pwendell** [comment]
@shivaram on the v3 idea... unfortunately we can't do that because v2 is already hard coded in the spark 0.9.0 release artifacts, which are immutable. it was my mistake for not first checking that the ec2 scripts wouldn't need to be upgraded in a major way before cutting the release (something I only realized after the fact).

**Comment by shivaram** [comment]
Ah - thats right.  I am actually not sure what our policy is for spark_ec2.py versions. For example the spark-version flag defaults to 0.8.0 right now in the scripts ( I noticed as I tried to test a 0.9 cluster but found it using 0.8) and the Spark->Shark mappings also lag behind a version.

Anyways as longs as things are backward compatible sticking to just v2 is fine

**Comment by pwendell** [comment]
I always bump the version before each spark release so it corresponds with
that release (though master it seems is out of date, 0.9, e.g., is
correct). The shark version lags mostly due to shark just not being
available... but once shark makes a release I go and add it to the s3
bucket. I just did this today for instance for Shark 0.8.1, so now users
who downloaded Spark 0.8.1 and run the ec2 script will get a version of
shark rather than an error message.

https://github.com/apache/incubator-spark/blob/branch-0.9/ec2/spark_ec2.py#L76

**Comment by shivaram** [comment]
Just to follow up on this -- @pwendell Can you update master's default spark version to 0.9.0 and also add a shark -> spark mapping ? I was writing some instructions on how to launch SparkR clusters and its easy to get confused if anybody uses the master branch

**Pull request merged**
