### PR TITLE
Update Apache download links

### PR DESCRIPTION
**Pull request by nchammas**
[Related discussion here.](http://apache-spark-developers-list.1001551.n3.nabble.com/create-image-sh-contains-broken-hadoop-web-link-td9128.html)

### CODE REVIEW

**Comment by nchammas** [comment]
cc @shivaram

**Comment by pwendell** [comment]
LGTM - however @nchammas do you want to fix the link for the maven download also? In both cases there I linked to specific apache mirrors, however, it would be better to link to the `dist` apache site which is more reliable.

**Comment by shivaram** [comment]
Thanks for the fix -- Could you also fix this in the v3 branch ?

**Comment by nchammas** [comment]
@pwendell I can do that (though the Maven link does currently work). You're right, it's probably better to have everything point to `dist`.

@shivaram Will do.

**Comment by pwendell** [comment]
Yeah so the issue is that the old link also used to work, but the
particular mirror went down. Overall dist is a more reliable source here.

**Comment by nchammas** [comment]
Maven link updated.

**Comment by pwendell** [comment]
Thanks I'll pull it in. @shivaram this is just a utility script hosted here it's not actually used anywhere in spark-ec2... do you think we need it in the earlier versions?

**Pull request merged**
